name: build and publish

on:
    workflow_call:

jobs:
    build-and-publish:
        name: Build and publish
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v3

            - name: Read .nvmrc
              run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
              id: nvm

            - uses: actions/setup-node@v3
              with:
                  node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
                  cache: npm
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@chrillaz'

            - run: npm ci
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
