name: development

on:
    push:
        tags:
            - '@chrillaz/*'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/github-script@v7
              env:
                  TAG: ${{ github.ref_name }}
              
              with:
                result-encoding: string
                script: |
                    const tag = process.env.TAG
                    return tag.match(/\w+(?=@)/)

            - run: echo ${{ steps.github-script.outputs.result }}
