name: publish

on:
    release:
        types: [published]
        branches: [main]

jobs:
    call-version-check:
        uses: './.github/workflows/version-check.yml'
    call-test:
        uses: './.github/workflows/test.yml'
    call-build-and-publish:
        uses: './.github/workflows/build-and-publish.yml'
