name: version check

on:
    workflow_call:

jobs:
    version-check:
        name: Version check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Package Version
              run: echo "VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)" >> $GITHUB_OUTPUT
              id: package

            - name: Compatible tag
              run: |
                  if ${{ github.ref_name }} != ${{ steps.package.outputs.VERSION }} ; then
                    echo "Package version: ${{ steps.package.outputs.VERSION }} incompatible with tag: ${{ github.ref_name }}"
                    exit 1
                  fi
